
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Blogs
{

    public Blogs()
    {

        this.Kinds = new HashSet<Kinds>();

        this.Post = new HashSet<Post>();

        this.Follows = new HashSet<Follows>();

    }


    public int Blog_ID { get; set; }

    public System.DateTime dataZalozenia { get; set; }

    public string status { get; set; }

    public System.DateTime dataAktualizacji { get; set; }

    public string nazwa { get; set; }

    public int UsersUser_ID { get; set; }

    public int followCount { get; set; }



    public virtual ICollection<Kinds> Kinds { get; set; }

    public virtual ICollection<Post> Post { get; set; }

    public virtual Users Users { get; set; }

    public virtual ICollection<Follows> Follows { get; set; }

}

}
