

//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BlogBazaContainer : DbContext
{
    public BlogBazaContainer()
        : base("name=BlogBazaContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Blogs> BlogsSet { get; set; }

    public DbSet<Kinds> KindsSet { get; set; }

    public DbSet<Comments> CommentsSet { get; set; }

    public DbSet<Post> PostSet { get; set; }

    public DbSet<Tags> TagsSet { get; set; }

    public DbSet<Users> UsersSet { get; set; }

    public DbSet<Votes> VotesSet { get; set; }

    public DbSet<Follows> FollowsSet { get; set; }

}

}

