
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comments
{

    public Comments()
    {

        this.Votes = new HashSet<Votes>();

    }


    public int Comment_ID { get; set; }

    public System.DateTime dataIGodzina { get; set; }

    public int upVotes { get; set; }

    public int Post_ID { get; set; }

    public int User_ID { get; set; }

    public string content { get; set; }

    public System.DateTime dataStworzenia { get; set; }

    public System.DateTime dataAktualizacji { get; set; }

    public int PostPost_ID { get; set; }



    public virtual Post Post { get; set; }

    public virtual ICollection<Votes> Votes { get; set; }

}

}
