
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Follows
{

    public int Follow_ID { get; set; }

    public int UsersUser_ID { get; set; }

    public int BlogsBlog_ID { get; set; }



    public virtual Blogs Blogs { get; set; }

    public virtual Users Users { get; set; }

}

}
