
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    public Post()
    {

        this.Comments = new HashSet<Comments>();

        this.Tags = new HashSet<Tags>();

    }


    public int Post_ID { get; set; }

    public System.DateTime dataStworzenia { get; set; }

    public string status { get; set; }

    public bool ifTop { get; set; }

    public System.DateTime dataAktualizacji { get; set; }

    public string text_content { get; set; }

    public string img_route { get; set; }

    public string title { get; set; }

    public string image_file_name { get; set; }

    public string image_content_type { get; set; }

    public int image_file_size { get; set; }

    public System.DateTime image_upload_Date { get; set; }

    public int BlogsBlog_ID { get; set; }



    public virtual Blogs Blogs { get; set; }

    public virtual ICollection<Comments> Comments { get; set; }

    public virtual ICollection<Tags> Tags { get; set; }

}

}
