
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tags
{

    public Tags()
    {

        this.Post = new HashSet<Post>();

    }


    public int Tag_ID { get; set; }

    public string tagName { get; set; }

    public System.DateTime dataStworzenia { get; set; }

    public System.DateTime dataAktualizacji { get; set; }



    public virtual ICollection<Post> Post { get; set; }

}

}
