
//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogProjekt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public Users()
    {

        this.Blogs = new HashSet<Blogs>();

        this.Follows = new HashSet<Follows>();

    }


    public int User_ID { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public string email { get; set; }

    public string phoneNumber { get; set; }

    public System.DateTime dataStworzenia { get; set; }

    public System.DateTime dataAktualizacji { get; set; }

    public bool isAdmin { get; set; }



    public virtual ICollection<Blogs> Blogs { get; set; }

    public virtual ICollection<Follows> Follows { get; set; }

}

}
